# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1088bc8e94c54c527d0426911aea5c8eca68697f692f018dd9b9bc35b084d666502e65b293c58a393fc41498deec6f72b5c904f439bb8dae6e3d8e0d203e96d2

test:
  secret_key_base: 6e70a7a6cfbaaf9b355c23bf0ddfd9a934748d23c9cf1609198a2afbde8fd626e4ef628b0642634cd618754478ee13785a73d56a4fdfc69b79c29cc805de7f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
